apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: adminer
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
      - adminer.gamma.dappy.tech
      secretName: dappy-node-tls
  rules:
    - host: adminer.gamma.dappy.tech
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: adminer
              port:
                number: 8080
