bases:
- ../../../../../base/dappy/pg

resources:
- dappy-node-webpki-ingress.yaml
- dappy-node-ingress.yaml
- dappy-node-service.yaml

patchesStrategicMerge:
- dappy-node-deployment.yaml

images:
  - name: fabcotech/dappy-node
    newName: fabcotech/dappy-node
    newTag: '3.33.7'
