parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: ./tsconfig.build.json
env:
  es2021: true
  jest: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - airbnb-base
  - airbnb-typescript/base
  - plugin:prettier/recommended
rules:
  import/no-extraneous-dependencies: off
settings:
  import/resolver:
    node:
      paths: ["."]
