services:
  dappy-node-migrations:
    image: fabcotech/dappy-node:3.33.7
    environment:
      - DAPPY_PG_CONNECTION_STRING=postgresql://postgres:postgres@172.17.0.1:5432/dappy
      - DAPPY_NODE_ZONE_PROVIDER=postgresql
    working_dir: "/app/packages/dappy-node/"
    command: ["npm", "run", "pg:migrate"]
  dappy-node:
    depends_on:
      dappy-node-migrations:
        condition: service_completed_successfully  
    image: fabcotech/dappy-node:3.33.7
    environment:
      - DAPPY_PG_CONNECTION_STRING=postgresql://postgres:postgres@172.17.0.1:5432/dappy
      - DAPPY_NODE_ZONE_PROVIDER=postgresql
      - DOWNLOAD_ZONES_IF_EMPTY=true
      - DAPPY_NETWORK_ID=gamma
      - DAPPY_NETWORK_MEMBER_TO_DOWNLOAD_ZONES_FROM=node1.gamma.fabco.dappy
      - DAPPY_NODE_ENABLE_REQUEST_METRICS=true
      - DAPPY_NODE_CACHING=0
      - DAPPY_NETWORK_MASTER_PUBLIC_KEY=04ea33c48dff95cdff4f4211780a5b151570a9a2fac5e62e5fa545c1aa5be3539c34d426b046f985204815964e10fcd1d87ef88d9bcf43816ad1fa00934cfe4652
    ports:
      - '3001:3001'
    command: ["node", "--max-old-space-size=8192", "/app/packages/dappy-node/dist/src/index.js"]
