apiVersion: apps/v1
kind: Deployment
metadata:
  name: dappy-node
spec:
  template:
    spec:
      initContainers:
        - name: pg-migrations
          env:
            - name: DAPPY_PG_CONNECTION_STRING
              value: postgresql://postgres:postgres@pg:5432/dappy
      containers:
        - name: dappy-node
          env:
            - name: DAPPY_PG_CONNECTION_STRING
              value: postgresql://postgres:postgres@pg:5432/dappy
