bases:
- ../../../../base/monitoring

resources:
- grafana-ingress.yaml
- grafana-configmap.yaml

patchesStrategicMerge:
- prometheus-pvc.yaml
- prometheus-clusterrolebinding.yaml
- prometheus-configmap.yaml
- grafana-pvc.yaml
