# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI dappy model

on:
  push:
    paths:
      - 'packages/dappy-model/**'
      - .github/workflows/ci-model.yaml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: npm
      - run: npm ci && npx lerna bootstrap
      - run: npx lerna run --scope=@fabcotech/dappy-model build

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache:  npm
      - run: npm ci && npx lerna bootstrap
      - run: npx lerna run --scope=@fabcotech/dappy-model lint
      - run: npx lerna run --scope=@fabcotech/dappy-model test
