# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI node

on:
  push:
    paths:
      - 'packages/node/**'
      - .github/workflows/ci-node.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci -w packages/node
      - run: npm run build -w packages/node

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: 'npm'
      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/".insteadOf
          ssh://git@github.com/
      - run: npm ci -w packages/node
      - run: npm run lint -w packages/node
      - run: npm test -w packages/node

  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Get package version
        run: echo "{package_version}={$(grep version ./packages/node/package.json | awk -F \" '{print $4}')}" >> $GITHUB_ENV
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./packages/node/Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/dappy-node:${{ env.package_version }}
