name: publish dappy-model

on: [workflow_dispatch]

jobs:
  npm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.target_commitish }}
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: npm
      - run: npm ci && npx lerna bootstrap
      - run: npx lerna run --scope=@fabcotech/dappy-model build
      - run: npx lerna run --scope=@fabcotech/dappy-model lint
      - run: npx lerna run --scope=@fabcotech/dappy-model test
      - run: npm config set '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_TOKEN }}"
      - run: npm publish
        working-directory: packages/dappy-model
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
