name: publish node

on: [workflow_dispatch]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Get package version
        run: echo "package_version=$(grep version ./packages/node/package.json | awk -F \" '{print $4}')" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./packages/node/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/dappy-node:${{ env.package_version }}
  npm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.target_commitish }}
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci -w packages/node
      - run: npm run build -w packages/node
      - run: npm publish -w packages/node
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
